#!/bin/ash

cd ofswitch-hwtable
./udatapath/ofdatapath --datapath-id=000000000012 --interfaces=eth1,eth2,eth3,eth4 ptcp:6632 --no-slicing &
./secchan/ofprotocol  tcp:127.0.0.1:6632 tcp:192.168.2.106:6633 &

echo "--------------------- openflow started ---------------------"
